import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { createPasswordService } from "./password-service.js";

// Hash gerado com bcrypt 5.1.1 (cost 12) antes do bump para 6.0.0.
// Serve de regressão: o formato bcrypt não mudou entre as versões, então um
// hash legado gravado no banco precisa continuar verificando.
const LEGACY_PLAIN_TEXT = "S3nh@Legada!2023";
const LEGACY_HASH_FROM_BCRYPT_5 =
  "$2b$12$/z96noDqNvtDhahNLJW50uL8Tzygu1PoEZEjJ9aX2W6Rhwk0LSqCG";

describe("PasswordService", () => {
  it("verifies a hash generated by the previous bcrypt major", async () => {
    const service = createPasswordService();
    assert.equal(await service.verify(LEGACY_PLAIN_TEXT, LEGACY_HASH_FROM_BCRYPT_5), true);
  });

  it("rejects a wrong password against a legacy hash", async () => {
    const service = createPasswordService();
    assert.equal(await service.verify("outra senha", LEGACY_HASH_FROM_BCRYPT_5), false);
  });

  it("hashes and verifies a new password", async () => {
    const service = createPasswordService();
    const hashed = await service.hash(LEGACY_PLAIN_TEXT);
    assert.notEqual(hashed, LEGACY_HASH_FROM_BCRYPT_5);
    assert.equal(await service.verify(LEGACY_PLAIN_TEXT, hashed), true);
  });
});
